version: "3.7"

services:
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ruby:
    build: .
    container_name: ruby_container
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/home/backend
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379

volumes:
  dbdata: