version: '3'

services: 
  react:
    build: .
    image: "node:14-alpine"
    command: npm run start
    container_name: react_container
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"        
    volumes: 
      - .:/frontend
      - /frontend/node_modules